[package]
name = "crypto_key_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
clap = { version = "4.5.20", features = ["derive"] }
hex = "0.4.3"
k256 = "0.13.4"
ripemd = "0.1.3"
sha2 = "0.10.8"
